Add Roles and User Groups to admin

diff --git a/client/Makefile b/client/Makefile
--- a/client/Makefile
+++ b/client/Makefile
@@ -5,19 +5,19 @@ WEB_SUBDIRS := $(filter %/, $(wildcard $(CURDIR)/web/*/))
 test:
 	@for dir in $(WEB_SUBDIRS); do \
 		echo "---Testing $$dir---"; \
-		(cd $$dir && yarn test:unit) || (echo "Failed to test $$dir"; exit 1); \
+		(cd $$dir && pnpm run test:unit) || (echo "Failed to test $$dir"; exit 1); \
 	done
 
 lint:
 	@for dir in $(WEB_SUBDIRS); do \
 		echo "---Linting $$dir---"; \
-		(cd $$dir && yarn lint) || (echo "Failed to lint $$dir"; exit 1); \
+		(cd $$dir && pnpm run lint) || (echo "Failed to lint $$dir"; exit 1); \
 	done
 
 build:
 	@for dir in $(WEB_SUBDIRS); do \
 		echo "---Building $$dir---"; \
-		(cd $$dir && yarn build) || (echo "Failed to build $$dir"; exit 1); \
+		(cd $$dir && pnpm run build) || (echo "Failed to build $$dir"; exit 1); \
 	done
 
 .DEFAULT_GOAL := dev
