Added 3 dev makefiles, use make dev on root to build and yarn libs/clients

diff --git a/client/Makefile b/client/Makefile
--- a/client/Makefile
+++ b/client/Makefile
@@ -1,12 +1,11 @@
-WEB_SUBDIRS := $(filter %/, $(wildcard web/*/))
+WEB_SUBDIRS := $(filter %/, $(wildcard $(CURDIR)/web/*/))
 
 .PHONY: yarn
 
 yarn:
 	@for dir in $(WEB_SUBDIRS); do \
-		echo "Entering $$dir"; \
-		cd $$dir && yarn; \
-		cd ../..; \
+		echo "---Yarning $$dir---"; \
+		(cd $$dir && yarn) || (echo "Failed to yarn $$dir"; exit 1); \
 	done
 
 .DEFAULT_GOAL := yarn
