Bump node to 22 and upgrade dependencies

diff --git a/client/Makefile b/client/Makefile
--- a/client/Makefile
+++ b/client/Makefile
@@ -1,6 +1,6 @@
 WEB_SUBDIRS := $(filter %/, $(wildcard $(CURDIR)/web/*/))
 
-.PHONY: dev
+.PHONY: dev test lint fresh
 
 yarn:
 	@for dir in $(WEB_SUBDIRS); do \
@@ -11,7 +11,25 @@ yarn:
 dev:
 	@for dir in $(WEB_SUBDIRS); do \
 		echo "---Installing and linking clients $$dir---"; \
-		(cd $$dir && yarn && yarn link @cortezaproject/corteza-js && yarn link @cortezaproject/corteza-vue) || (echo "Failed to run yarn or link libs $$dir"; exit 1); \
+		(cd $$dir && yarn && yarn cdeps) || (echo "Failed to run yarn or link libs $$dir"; exit 1); \
+	done
+
+test:
+	@for dir in $(WEB_SUBDIRS); do \
+		echo "---Testing $$dir---"; \
+		(cd $$dir && yarn test) || (echo "Failed to test $$dir"; exit 1); \
+	done
+
+lint:
+	@for dir in $(WEB_SUBDIRS); do \
+		echo "---Linting $$dir---"; \
+		(cd $$dir && yarn lint) || (echo "Failed to lint $$dir"; exit 1); \
+	done
+
+fresh:
+	@for dir in $(WEB_SUBDIRS); do \
+		echo "---Fresh $$dir---"; \
+		(cd $$dir && rm -rf node_modules yarn.lock && yarn && yarn cdeps) || (echo "Failed to fresh $$dir"; exit 1); \
 	done
 
 .DEFAULT_GOAL := dev
